services:
  base:
    image: 639347700193.dkr.ecr.ap-southeast-2.amazonaws.com/resi-lob/jdk21-eclipse-temurin
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - gradle-cache:/root/.gradle

  dev:
    extends: base
    command: ./gradlew bootRun
  test:
    extends: base
    command: ./gradlew check jacocoTestCoverageVerification

volumes:
  gradle-cache: